[package]
name = "voxentia"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
env_logger = "0.11.8"
gpu-allocator = "0.28.0"
log = "0.4.29"
nalgebra = "0.34.1"
winit = "0.30.12"
